# Enable mouse scroll
set -g mouse on

# Clipboard configuration
set -g set-clipboard on

# Increase history
set -g history-limit 5000

# Vim key bindings
set-window-option -g mode-keys vi

# Change prefix key from <C-b> to <C-g>
unbind C-b
set -g prefix C-g
bind C-g send-prefix

# Scroll with mouse
bind-key -T edit-mode-vi WheelUpPane send-keys -X scroll-up
bind-key -T edit-mode-vi WheelDownPane send-keys -X scroll-down

# vim-like copy mode
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'C-v' send -X rectangle-toggle
bind-key -T copy-mode-vi 'y' send -X copy-selection

# Synchronize copy buffer with clipboard
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -in"
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -in"

# split window command
bind \\ split-window -h
bind \- split-window -v

